"""Phase 6 — the `concolic` stage: hybrid concolic execution over the flagged sinks.

The fuzzer explores broadly but stalls at narrow checks (magic bytes, checksums, deep
branches). Concolic execution complements it: seed angr with the fuzzer's corpus, solve the
path constraints toward the statically-flagged sink sites, and emit concrete inputs that
reach them. Every generated input is then replayed in the Phase-4 sandbox -- a crash becomes
a Confirmed finding (same pipeline as fuzz/dynamic), a reached sink corroborates the static
finding, and the rest become new high-value seeds handed back to the fuzzer.

angr is an optional bundled tool run in its own interpreter; when it is absent the stage
fails clearly and the fuzzing stages remain the deterministic fallback.
"""
from __future__ import annotations

import base64

from ...db.dao import DynResultDAO, FindingDAO, TargetDAO
from ...jobs.registry import register_stage
from ..dynamic import sandbox
from ..dynamic.stage import crash_finding_candidate
from ..fuzz.directed import select_targets
from ..fuzz.runner import invocation
from . import concolic

CONCOLIC_STAGE = "concolic"
TOOL = "angr"
TOOL_VERSION = "angr-1"


def _gather_seeds(conn, target_id, limit=16):
    seen, out = set(), []
    for d in DynResultDAO(conn).list_by_target(target_id):
        if d.input_sha and d.input_sha not in seen:
            seen.add(d.input_sha)
            out.append(d.input_sha)
        if len(out) >= limit:
            break
    return out


def _corroborate_sink(conn, target, reached_addr):
    """A symbolically-generated input that reaches a flagged sink promotes that static
    finding to corroborated (a second channel now agrees it is reachable)."""
    fd = FindingDAO(conn)
    for f in fd.list_by_target(target.id):
        if f.site_addr == reached_addr and f.detector in (
                "dangerous_api", "weak_crypto", "weak_random", "insecure_tmp"):
            fd.upsert(target.id, target.case_id, {
                "cwe": f.cwe, "title": f.title, "severity": f.severity,
                "state": "corroborated", "confidence": max(f.confidence or 0.0, 0.7),
                "detector": f.detector, "function_addr": f.function_addr,
                "site_addr": f.site_addr, "dedup_key": f.dedup_key,
                "evidence": [{"channel": "symbolic",
                              "detail": "input reaching this sink generated by concolic "
                                        "execution (angr)"}]})
            return True
    return False


def concolic_stage(ctx) -> dict:
    target = TargetDAO(ctx.conn).get(ctx.target_id) if ctx.target_id else None
    if target is None:
        raise ValueError("concolic requires a target_id")

    p = ctx.params or {}
    py = concolic.locate_angr_python(p.get("angr_python"))
    if py is None:
        raise RuntimeError(
            "angr not found (looked at LYKOS_ANGR_PYTHON, a vendored venv, and python3 on "
            "PATH). Install angr, or use the fuzzing stages instead.")

    mode = p.get("input_mode", "stdin")               # stdin | arg | file
    input_size = int(p.get("input_size", 64))
    max_seconds = int(p.get("max_seconds", 120))
    exec_timeout = float(p.get("exec_timeout", 2))

    # targets: sink sites from static findings (site addr preferred), or explicit override
    if p.get("targets"):
        targets = list(p["targets"])
    else:
        ranked = select_targets(FindingDAO(ctx.conn).list_by_target(target.id))
        targets = []
        for t in ranked:
            a = t.get("site_addr") or t.get("function_addr")
            if a and a not in targets:
                targets.append(a)
        targets = targets[: int(p.get("max_targets", 8))]

    # seeds: prior dynamic/fuzz inputs (the hybrid handoff) plus any explicit ones
    seed_shas = _gather_seeds(ctx.conn, target.id)
    seeds_b64 = [base64.b64encode(ctx.content.get_bytes(s)).decode() for s in seed_shas]
    seeds_b64 += list(p.get("seeds", []))

    exe = ctx.scratch() / "target.bin"
    exe.write_bytes(ctx.content.path(target.sha256).read_bytes())
    exe.chmod(0o755)
    workfile = ctx.scratch() / "input.bin"

    spec = {"binary": str(exe), "input_mode": mode, "input_size": input_size,
            "targets": targets, "seeds": seeds_b64, "max_seconds": max_seconds,
            "num_find": int(p.get("num_find", 6)), "max_states": int(p.get("max_states", 800))}
    ctx.emit("concolic.start", payload={"targets": targets, "seeds": len(seeds_b64),
                                        "mode": mode, "angr_python": str(py)})
    ctx.progress(msg=f"concolic exploration toward {len(targets)} target(s)")

    res = concolic.run_explore(py, spec, ctx=ctx, timeout=max_seconds)
    ctx.emit("concolic.explored", payload={
        "reached": res.get("reached_targets", []), "generated": len(res.get("generated", [])),
        "stats": res.get("stats", {}), "angr_version": res.get("angr_version")})

    fd = FindingDAO(ctx.conn)
    dd = DynResultDAO(ctx.conn)
    confirmed = corroborated = new_seeds = 0
    seen_sigs = set()

    for g in res.get("generated", []):
        if ctx.should_cancel():
            break
        data = base64.b64decode(g["input_b64"])
        argv, stdin = invocation(mode, workfile, data)
        r = sandbox.run(exe, argv=argv, stdin=(stdin if mode == "stdin" else b""),
                        timeout=exec_timeout, arch=target.arch)
        input_sha = ctx.put_artifact("concolic-input", data=data)
        dd.insert(target.id, target.case_id, run_id=ctx.run_id, input_sha=input_sha,
                  input_mode=mode, argv=argv, exit_code=r.exit_code, signal=r.signal,
                  signal_name=r.signal_name, crashed=r.crashed, isolation=r.isolation,
                  duration_ms=r.duration_ms,
                  note="concolic-generated" + (f"; reached {g['reached']}"
                                               if g.get("reached") else ""))
        if r.crashed:
            if r.signal_name not in seen_sigs:
                seen_sigs.add(r.signal_name)
                fd.upsert(target.id, target.case_id, crash_finding_candidate(
                    r.signal_name, input_sha, r.isolation, "concolic",
                    "(generated by concolic execution)"))
            confirmed += 1
        elif g.get("reached") and g["reached"] not in (None, "unconstrained-ip"):
            if _corroborate_sink(ctx.conn, target, g["reached"]):
                corroborated += 1
        else:
            new_seeds += 1

    ctx.emit("concolic.done", payload={"confirmed": confirmed, "corroborated": corroborated,
                                       "new_seeds": new_seeds,
                                       "reached": res.get("reached_targets", [])})
    ctx.progress(pct=100, msg=f"{confirmed} crashes, {corroborated} corroborated, "
                             f"{new_seeds} new seeds")
    return {}


def register() -> None:
    register_stage(CONCOLIC_STAGE, concolic_stage, resource_class="cpu", tool=TOOL,
                   tool_version=TOOL_VERSION, timeout=3600)


def enqueue_concolic(queue, target, *, params=None, force: bool = True):
    return queue.enqueue(target.case_id, CONCOLIC_STAGE, target_id=target.id,
                         params=params or {}, input_hashes=[target.sha256], tool=TOOL,
                         tool_version=TOOL_VERSION, resource_class="cpu", force=force)
