"""Phase 6 — the `concolic` stage: hybrid concolic execution with a selectable backend.

The fuzzer explores broadly but stalls at narrow checks (magic bytes, checksums, deep
branches). Concolic execution complements it by solving path constraints and emitting concrete
inputs. Two backends, chosen by params.backend ("auto" | "angr" | "symqemu"):

  * angr    -- symbolic exploration steered toward the statically-flagged sink sites; can
               report which sink an input reaches (corroborating the static finding).
  * symqemu -- QEMU-based concolic execution seeded by the fuzzer corpus; fast, source-free,
               generates new inputs by flipping branches along the concrete path.

Every generated input is replayed in the Phase-4 sandbox: a crash becomes a Confirmed finding,
a reached sink corroborates the static finding, and the rest become new seeds for the fuzzer.
Both backends are optional bundled tools; the stage fails clearly when the requested backend
is unavailable and the fuzzing stages remain the deterministic fallback.
"""
from __future__ import annotations

import base64

from ...db.dao import DynResultDAO, FindingDAO, TargetDAO
from ...jobs.registry import register_stage
from ..dynamic import sandbox
from ..dynamic.stage import crash_finding_candidate
from ..fuzz.directed import select_targets
from ..fuzz.runner import invocation
from . import concolic, symqemu

CONCOLIC_STAGE = "concolic"
TOOL = "concolic"
TOOL_VERSION = "concolic-1"


def _gather_seeds(conn, target_id, limit=16):
    seen, out = set(), []
    for d in DynResultDAO(conn).list_by_target(target_id):
        if d.input_sha and d.input_sha not in seen:
            seen.add(d.input_sha)
            out.append(d.input_sha)
        if len(out) >= limit:
            break
    return out


def _corroborate_sink(conn, target, reached_addr):
    """A symbolically-generated input that reaches a flagged sink promotes that static
    finding to corroborated (a second channel now agrees it is reachable)."""
    fd = FindingDAO(conn)
    for f in fd.list_by_target(target.id):
        if f.site_addr == reached_addr and f.detector in (
                "dangerous_api", "weak_crypto", "weak_random", "insecure_tmp"):
            fd.upsert(target.id, target.case_id, {
                "cwe": f.cwe, "title": f.title, "severity": f.severity,
                "state": "corroborated", "confidence": max(f.confidence or 0.0, 0.7),
                "detector": f.detector, "function_addr": f.function_addr,
                "site_addr": f.site_addr, "dedup_key": f.dedup_key,
                "evidence": [{"channel": "symbolic",
                              "detail": "input reaching this sink generated by concolic "
                                        "execution"}]})
            return True
    return False


def _validate(ctx, target, exe, mode, workfile, generated, exec_timeout):
    """Replay each generated input in the sandbox and record crashes / corroborations /
    seeds. `generated` items are dicts: {input_b64, reached?}. Returns counts."""
    fd = FindingDAO(ctx.conn)
    dd = DynResultDAO(ctx.conn)
    confirmed = corroborated = new_seeds = 0
    seen_sigs = set()
    for g in generated:
        if ctx.should_cancel():
            break
        data = base64.b64decode(g["input_b64"])
        argv, stdin = invocation(mode, workfile, data)
        r = sandbox.run(exe, argv=argv, stdin=(stdin if mode == "stdin" else b""),
                        timeout=exec_timeout, arch=target.arch)
        input_sha = ctx.put_artifact("concolic-input", data=data)
        dd.insert(target.id, target.case_id, run_id=ctx.run_id, input_sha=input_sha,
                  input_mode=mode, argv=argv, exit_code=r.exit_code, signal=r.signal,
                  signal_name=r.signal_name, crashed=r.crashed, isolation=r.isolation,
                  duration_ms=r.duration_ms,
                  note="concolic-generated" + (f"; reached {g['reached']}"
                                               if g.get("reached") else ""))
        if r.crashed:
            if r.signal_name not in seen_sigs:
                seen_sigs.add(r.signal_name)
                fd.upsert(target.id, target.case_id, crash_finding_candidate(
                    r.signal_name, input_sha, r.isolation, "concolic",
                    "(generated by concolic execution)"))
            confirmed += 1
        elif g.get("reached") and g["reached"] not in (None, "unconstrained-ip"):
            if _corroborate_sink(ctx.conn, target, g["reached"]):
                corroborated += 1
        else:
            new_seeds += 1
    return confirmed, corroborated, new_seeds


def _choose_backend(p, target):
    """Return (backend, angr_python, symqemu_path). Honors params.backend; auto prefers angr
    (directed, sink-aware) then symqemu."""
    want = p.get("backend", "auto")
    py = concolic.locate_angr_python(p.get("angr_python")) if want in ("auto", "angr") else None
    sq = (symqemu.locate_symqemu(p.get("symqemu_path"), target.arch or "x86-64")
          if want in ("auto", "symqemu") else None)
    if want == "angr":
        return ("angr", py, None) if py else (None, None, None)
    if want == "symqemu":
        return ("symqemu", None, sq) if sq else (None, None, None)
    if py:
        return "angr", py, None
    if sq:
        return "symqemu", None, sq
    return None, None, None


def _run_angr(ctx, target, exe, mode, p, py):
    input_size = int(p.get("input_size", 64))
    max_seconds = int(p.get("max_seconds", 120))
    if p.get("targets"):
        targets = list(p["targets"])
    else:
        ranked = select_targets(FindingDAO(ctx.conn).list_by_target(target.id))
        targets = []
        for t in ranked:
            a = t.get("site_addr") or t.get("function_addr")
            if a and a not in targets:
                targets.append(a)
        targets = targets[: int(p.get("max_targets", 8))]
    seed_shas = _gather_seeds(ctx.conn, target.id)
    seeds_b64 = [base64.b64encode(ctx.content.get_bytes(s)).decode() for s in seed_shas]
    seeds_b64 += list(p.get("seeds", []))
    spec = {"binary": str(exe), "input_mode": mode, "input_size": input_size,
            "targets": targets, "seeds": seeds_b64, "max_seconds": max_seconds,
            "num_find": int(p.get("num_find", 6)), "max_states": int(p.get("max_states", 800))}
    ctx.emit("concolic.start", payload={"backend": "angr", "targets": targets,
                                        "seeds": len(seeds_b64), "mode": mode})
    ctx.progress(msg=f"angr exploration toward {len(targets)} target(s)")
    res = concolic.run_explore(py, spec, ctx=ctx, timeout=max_seconds)
    ctx.emit("concolic.explored", payload={"backend": "angr",
             "reached": res.get("reached_targets", []),
             "generated": len(res.get("generated", [])),
             "stats": res.get("stats", {}), "angr_version": res.get("angr_version")})
    return res.get("generated", []), res.get("reached_targets", [])


def _run_symqemu(ctx, target, exe, mode, base_argv, p, sq):
    max_seconds = int(p.get("max_seconds", 120))
    seed_shas = _gather_seeds(ctx.conn, target.id)
    seeds = [ctx.content.get_bytes(s) for s in seed_shas]
    seeds += [base64.b64decode(x) for x in p.get("seeds", [])]
    ctx.emit("concolic.start", payload={"backend": "symqemu", "seeds": len(seeds),
                                        "mode": mode})
    ctx.progress(msg=f"symqemu concolic from {len(seeds)} seed(s)")
    gen = symqemu.run_campaign(sq, exe, seeds, ctx.scratch(),
                               mode=("file" if mode != "stdin" else "stdin"),
                               base_argv=base_argv, rounds=int(p.get("rounds", 2)),
                               timeout=max(10, max_seconds // 4),
                               cap=int(p.get("num_find", 64)), ctx=ctx)
    generated = [{"input_b64": base64.b64encode(d).decode(), "reached": None} for d in gen]
    ctx.emit("concolic.explored", payload={"backend": "symqemu",
             "generated": len(generated), "reached": []})
    return generated, []


def concolic_stage(ctx) -> dict:
    target = TargetDAO(ctx.conn).get(ctx.target_id) if ctx.target_id else None
    if target is None:
        raise ValueError("concolic requires a target_id")
    p = ctx.params or {}
    mode = p.get("input_mode", "stdin")
    base_argv = list(p.get("argv") or [])
    exec_timeout = float(p.get("exec_timeout", 2))

    backend, py, sq = _choose_backend(p, target)
    if backend is None:
        raise RuntimeError(
            "no concolic backend available: angr (LYKOS_ANGR_PYTHON / vendored venv / python3) "
            "and symqemu (LYKOS_SYMQEMU / vendored / PATH) were both not found. Install one, "
            "or use the fuzzing stages instead.")

    exe = ctx.scratch() / "target.bin"
    exe.write_bytes(ctx.content.path(target.sha256).read_bytes())
    exe.chmod(0o755)
    workfile = ctx.scratch() / "input.bin"

    if backend == "angr":
        generated, reached = _run_angr(ctx, target, exe, mode, p, py)
    else:
        generated, reached = _run_symqemu(ctx, target, exe, mode, base_argv, p, sq)

    confirmed, corroborated, new_seeds = _validate(ctx, target, exe, mode, workfile,
                                                   generated, exec_timeout)
    ctx.emit("concolic.done", payload={"backend": backend, "confirmed": confirmed,
                                       "corroborated": corroborated, "new_seeds": new_seeds,
                                       "reached": reached})
    ctx.progress(pct=100, msg=f"[{backend}] {confirmed} crashes, {corroborated} corroborated, "
                             f"{new_seeds} new seeds")
    return {}


def register() -> None:
    register_stage(CONCOLIC_STAGE, concolic_stage, resource_class="cpu", tool=TOOL,
                   tool_version=TOOL_VERSION, timeout=3600)


def enqueue_concolic(queue, target, *, params=None, force: bool = True):
    return queue.enqueue(target.case_id, CONCOLIC_STAGE, target_id=target.id,
                         params=params or {}, input_hashes=[target.sha256], tool=TOOL,
                         tool_version=TOOL_VERSION, resource_class="cpu", force=force)
